# default configuration
baseURL = "https://shyamh.com/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Shyam Hari"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.main]]
URL = "about"
name = "About"
weight = 1

[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2

# default parameters
[params]
home = "Home"
logo = ""
# theme color
theme_color = "#05befc"
# contact info
phone = "+1 217 650 9576"
email = "shyamh@stanford.edu"
address = "Stanford University"
# meta description
description = "This is meta description"

# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format


# social site
[[params.social]]
icon = "ti-linkedin"
URL = "https://www.linkedin.com/in/shyamh2/"
